# docker-compose.yml

version: '3'

services:

  client:
    build: build
    environment:
      - ISSUER=${ISSUER_SERVER_URL}:${ISSUER_SERVER_PORT}

      - RESOURCE_SERVER=${RESOURCE_SERVER_URL}:${RESOURCE_SERVER_PORT}

      - MY_URL=${CLIENT_URL}:${CLIENT_PORT}

      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

      - LOG_LEVEL=${LOG_LEVEL:-ERROR}
    ports:
      - ${CLIENT_PORT}:80
    volumes:
      - ./src/client:/app

  issuer:
    build: build
    environment:
      - MY_URL=${ISSUER_SERVER_URL}:${ISSUER_SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${ISSUER_SERVER_PORT}:80
    volumes:
      - ./src/issuer:/app

  resource:
    build: build
    environment:
      - ISSUER=${ISSUER_SERVER_URL}:${ISSUER_SERVER_PORT}
      - RESOURCE_API_URL=${RESOURCE_API_URL}
      - RESOURCE_API_KEY=${RESOURCE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${RESOURCE_SERVER_PORT}:80
    volumes:
      - ./src/resource:/app
