# docker-compose.yml

version: '3'

services:

  client:
    build: build
    environment:
      - ISSUER=http://host.docker.internal:${ISSUER_SERVER_PORT}

      - RESOURCE_SERVER=http://host.docker.internal:${RESOURCE_SERVER_PORT}

      - MY_URL=http://host.docker.internal:${CLIENT_PORT}

      - CLIENT_ID=sample-client-id
      - CLIENT_SECRET=sample-client-secret

      - LOG_LEVEL=${LOG_LEVEL}
    extra_hosts:
      - localhost:host-gateway
    ports:
      - ${CLIENT_PORT}:80
    volumes:
      - ./src/client:/app

  issuer:
    build: build
    environment:
      - MY_URL=http://host.docker.internal:${ISSUER_SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
    extra_hosts:
      - localhost:host-gateway
    ports:
      - ${ISSUER_SERVER_PORT}:80
    volumes:
      - ./src/issuer:/app

  resource:
    build: build
    environment:
      - ISSUER=http://host.docker.internal:${ISSUER_SERVER_PORT}
      - RESOURCE_API_URL=${RESOURCE_API_URL}
      - RESOURCE_API_KEY=${RESOURCE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${RESOURCE_SERVER_PORT}:80
    volumes:
      - ./src/resource:/app
